apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-carrier
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-carrier
  chart:
    git: git@github.com:fazhong/bevel.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://47.242.153.200:8200
      authpath: devcarrier-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      CsoCChgKFggCGgYIt/GLjgYiCmFsbGNoYW5uZWwSrQIKqgIKCmFsbGNoYW5uZWwSYxJhCgtBcHBs
      aWNhdGlvbhJSCAESTgoKY2Fycmllck1TUBJAGgcKA01TUBIAIgoKBkFkbWlucxIAIg8KC0VuZG9y
      c2VtZW50EgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSABq2ARKzAQoLQXBwbGljYXRpb24SowEI
      ARKeAQoKY2Fycmllck1TUBKPAQgBGkMKC0FuY2hvclBlZXJzEjQSKgooCiNwZWVyMC5jYXJyaWVy
      LW5ldC5wZWVyMC5jYXJyaWVyLW5ldBD7QRoGQWRtaW5zGgcKA01TUBIAIgoKBkFkbWlucxIAIg8K
      C0VuZG9yc2VtZW50EgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACoGQWRtaW5z

