apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: git@github.com:fazhong/bevel.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://47.242.153.200:8200
      role: vault-role
      authpath: devsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: orderer1.supplychain-net

    genesis: |-
      CiIaIK3tgC+DmvUea6quziB8Btx7xRVpbttrkU/Q+WuQm2vKEvNYCvBYCu1YCngKWggBEAEaBgiK
      gYuOBiIKc3lzY2hhbm5lbCpAYzhjZDkzNzE5ZjVhOTVkMjc2OGMzYjY4ZWRhY2M2ZGUxNzdiNmE0
      MmMyNzA0YTJlMjQwNWYyNDQ2YTk3YjU2MxIaEhgqUenKfX58+1APMPJviba20MTl+JBBKZoS8FcK
      7VcS6lcSrisKB09yZGVyZXISoisSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVRm41N2lpK0trRHpzMDl2dDl2Nk0wTEY1cXVZd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeU1EVTFOREV6V2hjTk1qUXhNREV4TURVMU5ERXpX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJETjBP
      MHNuYXJlaGlvbS9pS2hYaTU5UzBUL3VvcDNlYXdkbDBMeTdlUDhManR4MG5ucHIKSkY5Q0ozWEtR
      czBZb21ZS0dqQmYvdTI4a1ptck14aGZxcVdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVDVjbFVEcERTMGdwaWQ4aDdSK1hMUHZF
      RExmREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTVTUmY1L3haaFY1MkxQU2FWYkREUTRJY2V0
      OVV4c3dNQS9iTkZFVjAKVUFRQ0lFRTBVb0h0clVhU1ZRMmMrR3M1Z2hLdWZ4L2UrMmlRbHEwWHQ5
      YUhReFUzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0akNDQW9pZ0F3SUJBZ0lVUWQ5d0RtTE9ROWN2cEh0Z2dZR25JRjQzS2kwd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakV4TWpJeU1EVTFPVEF3V2hjTk1q
      SXhNakl5TURZd05EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFQ0JySkJzY2owbnVkL3BXTjQ5Wlh0TnFray9x
      TlZyRlQKWE9CNHA0Q1ZJTENxQWViTnZLREpITGVRQlJQNHJmajl5Y1VleXE5U2tJR2xERnZ0Vnpy
      SEhhT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJTVkVHSkpPRmRrCkFMdmpBZk5Gd29yMkZlTTFZakFmQmdOVkhTTUVHREFXZ0JU
      NWNsVURwRFMwZ3BpZDhoN1IrWExQdkVETGZEQWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      M05XTm1OMkptWm1SaUxXSnVjbUo0TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      U0FBdwpSUUloQVBMS3hzbUVPb1k3Y21KL0lENmJIODlsWE9iY21paEpON1BiNFZ6ZWNDajRBaUJZ
      dWlxSWRDRjZoR3lSCkVSUlcyUC95Wm5acVNqTVhvM3VoTk9Jbzd4SnJ2Zz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVUZuNTdpaStLa0R6czA5dnQ5djZNMExGNXF1WXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpFeE1qSXlNRFUxTkRFeldoY05NalF4
      TURFeE1EVTFOREV6V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCRE4wTzBzbmFyZWhpb20vaUtoWGk1OVMwVC91b3AzZWF3ZGwwTHk3ZVA4TGp0eDBu
      bnByCkpGOUNKM1hLUXMwWW9tWUtHakJmL3UyOGtabXJNeGhmcXFXalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlQ1Y2xVRHBEUzBn
      cGlkOGg3UitYTFB2RURMZkRBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE1U1JmNS94WmhWNTJM
      UFNhVmJERFE0SWNldDlVeHN3TUEvYk5GRVYwClVBUUNJRUUwVW9IdHJVYVNWUTJjK0dzNWdoS3Vm
      eC9lKzJpUWxxMFh0OWFIUXhVMwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjsK
      C0VuZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiQK
      DENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMaoxIKDUNvbnNlbnN1c1R5cGUSkRIS
      hhIKCGV0Y2RyYWZ0EvkRCuIRCiFvcmRlcmVyMS5vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQQ+0Ea
      2wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRENqQ0NBckNnQXdJQkFnSVVCanVtYVlO
      cy9OWXpuOGltZWlCZmhyN0xJVW93Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJ
      eER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFR
      S0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhj
      Tk1qRXhNakl5TURVMU9UQXdXaGNOTWpJeE1qSXlNRFl3TkRBd1dqQnhNUXN3Q1FZRFZRUUdFd0pI
      UWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQ
      Y21SbGNtVnlNUkF3CkRnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5
      TVM1emRYQndiSGxqYUdGcGJpMXUKWlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05D
      QUFTejdSTDU0MjJUTUF6UlYwRlIyeW9yMW5sTAovWmdXeGtBeDNkK2QwY2RablBlVjdaNlVhZEdu
      OGg0TjNSbUxLaFBJYWNtQ1RHVUdLREQreFl1UEkrTVBvNElCCk56Q0NBVE13RGdZRFZSMFBBUUgv
      QkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQU1CZ05W
      SFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJTUHp0c2Q5RHRibDgxOVZ5VnRFY2dUM05DNgpuakFm
      QmdOVkhTTUVHREFXZ0JUNWNsVURwRFMwZ3BpZDhoN1IrWExQdkVETGZEQkdCZ05WSFJFRVB6QTln
      aGh2CmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDSVc5eVpHVnlaWEl4TG05eVpHVnla
      WEl4TG5OMWNIQnMKZVdOb1lXbHVMVzVsZERCc0JnZ3FBd1FGQmdjSUFRUmdleUpoZEhSeWN5STZl
      eUpvWmk1QlptWnBiR2xoZEdsdgpiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJKUkNJNkltOXla
      R1Z5WlhJeExuTjFjSEJzZVdOb1lXbHVMVzVsCmRDSXNJbWhtTGxSNWNHVWlPaUp2Y21SbGNtVnlJ
      bjE5TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDaUI5V3kKUDhEYUt4Ti9GbXpEZDYrZzREZktO
      WTdONWltcFFVb2pUZ21WUlFJZ0VxOGtNUnpmaFJKYVRWWnNwcit0aW00cwo4RlplQ2lJUjVlR2xM
      M29pUlFFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLbCC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlEQ2pDQ0FyQ2dBd0lCQWdJVUJqdW1hWU5zL05Zem44aW1laUJmaHI3TElVb3dD
      Z1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURW
      UVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpFeE1qSXlNRFUxT1RBd1doY05N
      akl4TWpJeU1EWXdOREF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVO
      VEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxF
      d2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVN6N1JMNTQyMlRNQXpSVjBGUjJ5
      b3IxbmxMCi9aZ1d4a0F4M2QrZDBjZFpuUGVWN1o2VWFkR244aDROM1JtTEtoUElhY21DVEdVR0tE
      RCt4WXVQSStNUG80SUIKTnpDQ0FUTXdEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01C
      UUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERn
      UVdCQlNQenRzZDlEdGJsODE5VnlWdEVjZ1QzTkM2Cm5qQWZCZ05WSFNNRUdEQVdnQlQ1Y2xVRHBE
      UzBncGlkOGg3UitYTFB2RURMZkRCR0JnTlZIUkVFUHpBOWdoaHYKY21SbGNtVnlNUzV6ZFhCd2JI
      bGphR0ZwYmkxdVpYU0NJVzl5WkdWeVpYSXhMbTl5WkdWeVpYSXhMbk4xY0hCcwplV05vWVdsdUxX
      NWxkREJzQmdncUF3UUZCZ2NJQVFSZ2V5SmhkSFJ5Y3lJNmV5Sm9aaTVCWm1acGJHbGhkR2x2CmJp
      STZJaUlzSW1obUxrVnVjbTlzYkcxbGJuUkpSQ0k2SW05eVpHVnlaWEl4TG5OMWNIQnNlV05vWVds
      dUxXNWwKZENJc0ltaG1MbFI1Y0dVaU9pSnZjbVJsY21WeUluMTlNQW9HQ0NxR1NNNDlCQU1DQTBn
      QU1FVUNJUUNpQjlXeQpQOERhS3hOL0ZtekRkNitnNERmS05ZN041aW1wUVVvalRnbVZSUUlnRXE4
      a01SemZoUkphVFZac3ByK3RpbTRzCjhGWmVDaUlSNWVHbEwzb2lSUUU9Ci0tLS0tRU5EIENFUlRJ
      RklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICAgAgaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgD
      EgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIi
      CgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxIN
      CAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMS7CkKC0NvbnNvcnRpdW1zEtwpEpEpChVTdXBw
      bHlDaGFpbkNvbnNvcnRpdW0S9ygSmSgKCmNhcnJpZXJNU1ASiigapiYKA01TUBKeJhKTJhKQJgoK
      Y2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lC
      QWdJVUZsOFp6RkJBZUt6dW1jMVdMcDdvdDhUOGh4RXdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxk
      REFlRncweQpNVEV5TWpJd05UVTJNVFphRncweU5ERXdNVEV3TlRVMk1UWmFNRm94Q3pBSkJnTlZC
      QVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFN
      QTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdX
      VEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFpclVTTzRSeFdXNk1HK1ptK1VDQlZn
      ZDlHTkRmQ2FlaFlRbjQ3ZjNQR0xBanVYQkF2MkRjOWxXR05Hc25DCkNZbmtCRzAxNUNLNjdteVZH
      MmRhUytSTG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJw
      akFkQmdOVkhRNEVGZ1FVc0RlaHJLT2c2UjA4VUF1aU80ejNoMUY1bHVZd0NnWUlLb1pJemowRQpB
      d0lEU0FBd1JRSWhBT3ozaFpHTy9PamllRno5byt2RmdFRkV6MmpBcDRtSmRMRTlKcWMrZVV5bkFp
      QmVTQzhqCjBCSHVQTGFFOUhMWkRVQU1uM1FIRlNYR2R3Z0UwWG9BcWcyRjVRPT0KLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoisggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzdUQ0NB
      cFNnQXdJQkFnSVVmTkE2REM4dGEvK25XWnZibXZjaFpnWDBuSHN3Q2dZSUtvWkl6ajBFQXdJdwpX
      akVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RH
      OXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFX
      VnlMVzVsZERBZUZ3MHkKTVRFeU1qSXdOakF5TURCYUZ3MHlNakV5TWpJd05qQTNNREJhTUhneEN6
      QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVE
      QU9CZ05WQkFvVEIwOXlaR1Z5WlhJeEhqQU1CZ05WCkJBc1RCV0ZrYldsdU1BNEdBMVVFQ3hNSFky
      RnljbWxsY2pFYU1CZ0dBMVVFQXd3UlFXUnRhVzVBWTJGeWNtbGwKY2kxdVpYUXdXVEFUQmdjcWhr
      ak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVFZiVkZWYUpjaHlBVzhwYVFGV3JVbgovVDJpSmg0eEdX
      NWxMbFlnb1o5UUJaTUl6K0xmcms0TEh3bmJKUHdwbW1jRjV4UWQ2REJZaTdBczVBVkpHbmE2Cm80
      SUJHRENDQVJRd0RnWURWUjBQQVFIL0JBUURBZ2VBTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIw
      T0JCWUUKRkFPbjZiakdibjlqYUJxc3M1OXZRYUJtQnVtU01COEdBMVVkSXdRWU1CYUFGTEEzb2F5
      am9Pa2RQRkFMb2p1TQo5NGRSZVpibU1DUUdBMVVkRVFRZE1CdUNHV05oTFhSdmIyeHpMVFkyTm1Z
      M09EUm1PVGd0ZGpscWVIUXdnWTBHCkNDb0RCQVVHQndnQkJJR0FleUpoZEhSeWN5STZleUpoWW1G
      akxtbHVhWFFpT2lKMGNuVmxJaXdpWVdSdGFXNGkKT2lKMGNuVmxJaXdpYUdZdVFXWm1hV3hwWVhS
      cGIyNGlPaUpqWVhKeWFXVnlJaXdpYUdZdVJXNXliMnhzYldWdQpkRWxFSWpvaVFXUnRhVzVBWTJG
      eWNtbGxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJCktvWkl6ajBFQXdJ
      RFJ3QXdSQUlnVE5uQ1p5NDRGcTNRNE92clRjZWlOYUVTcmFqQ000WE9oNHZ2Q1d0L0g3WUMKSUE1
      UHpkcmRyd2dQZ2w2M1E1UEpMV0kzQlhsV3BzbW56S2tqblF3UmwxbHcKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUIrRENDQVo2Z0F3SUJBZ0lVRmw4WnpGQkFlS3p1bWMxV0xwN290OFQ4aHhFd0NnWUlLb1pJ
      emowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVq
      WVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1URXlNakl3TlRVMk1UWmFGdzB5TkRFd01URXdOVFUy
      TVRaYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05W
      QkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEpsY2pFWApNQlVHQTFVRUF3d09ZMkV1
      WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUWlyVVNP
      NFJ4V1c2TUcrWm0rVUNCVmdkOUdORGZDYWVoWVFuNDdmM1BHTEFqdVhCQXYyRGM5bFdHTkdzbkMK
      Q1lua0JHMDE1Q0s2N215VkcyZGFTK1JMbzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdB
      MVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVzRGVocktPZzZSMDhVQXVpTzR6M2gxRjVs
      dVl3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFPejNoWkdPL09qaWVGejlvK3ZGZ0VGRXoyakFw
      NG1KZExFOUpxYytlVXluQWlCZVNDOGoKMEJIdVBMYUU5SExaRFVBTW4zUUhGU1hHZHdnRTBYb0Fx
      ZzJGNVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tClrkEQgBEvQFCukFLS0tLS1CRUdJTiBD
      RVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVRmw4WnpGQkFlS3p1bWMxV0xwN290
      OFQ4aHhFd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01C
      a3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlN
      UmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1URXlNakl3TlRVMk1UWmFG
      dzB5TkRFd01URXdOVFUyTVRaYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4d0RRWUQKVlFRSURBWk1i
      MjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3SFQzSmtaWEpsY2pFWApN
      QlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BR
      TUJCd05DCkFBUWlyVVNPNFJ4V1c2TUcrWm0rVUNCVmdkOUdORGZDYWVoWVFuNDdmM1BHTEFqdVhC
      QXYyRGM5bFdHTkdzbkMKQ1lua0JHMDE1Q0s2N215VkcyZGFTK1JMbzBJd1FEQVBCZ05WSFJNQkFm
      OEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0RUZnUVVzRGVocktPZzZS
      MDhVQXVpTzR6M2gxRjVsdVl3Q2dZSUtvWkl6ajBFCkF3SURTQUF3UlFJaEFPejNoWkdPL09qaWVG
      ejlvK3ZGZ0VGRXoyakFwNG1KZExFOUpxYytlVXluQWlCZVNDOGoKMEJIdVBMYUU5SExaRFVBTW4z
      UUhGU1hHZHdnRTBYb0FxZzJGNVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChIGY2xpZW50
      GvIFCukFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIrRENDQVo2Z0F3SUJBZ0lVRmw4
      WnpGQkFlS3p1bWMxV0xwN290OFQ4aHhFd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhN
      Q1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZ
      RFZRUUtEQWRQY21SbGNtVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5
      Ck1URXlNakl3TlRVMk1UWmFGdzB5TkRFd01URXdOVFUyTVRaYU1Gb3hDekFKQmdOVkJBWVRBa2RD
      TVE4d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVF
      Q2d3SFQzSmtaWEpsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2Nx
      aGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBUWlyVVNPNFJ4V1c2TUcrWm0rVUNCVmdkOUdORGZD
      YWVoWVFuNDdmM1BHTEFqdVhCQXYyRGM5bFdHTkdzbkMKQ1lua0JHMDE1Q0s2N215VkcyZGFTK1JM
      bzBJd1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05W
      SFE0RUZnUVVzRGVocktPZzZSMDhVQXVpTzR6M2gxRjVsdVl3Q2dZSUtvWkl6ajBFCkF3SURTQUF3
      UlFJaEFPejNoWkdPL09qaWVGejlvK3ZGZ0VGRXoyakFwNG1KZExFOUpxYytlVXluQWlCZVNDOGoK
      MEJIdVBMYUU5SExaRFVBTW4zUUhGU1hHZHdnRTBYb0FxZzJGNVE9PQotLS0tLUVORCBDRVJUSUZJ
      Q0FURS0tLS0tChIEcGVlciLzBQrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RD
      Q0FaNmdBd0lCQWdJVUZsOFp6RkJBZUt6dW1jMVdMcDdvdDhUOGh4RXdDZ1lJS29aSXpqMEVBd0l3
      CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5
      YVdWeUxXNWxkREFlRncweQpNVEV5TWpJd05UVTJNVFphRncweU5ERXdNVEV3TlRVMk1UWmFNRm94
      Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2
      Ym1SdmJqRVFNQTRHQTFVRUNnd0hUM0prWlhKbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxs
      Y2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFpclVTTzRSeFdXNk1H
      K1ptK1VDQlZnZDlHTkRmQ2FlaFlRbjQ3ZjNQR0xBanVYQkF2MkRjOWxXR05Hc25DCkNZbmtCRzAx
      NUNLNjdteVZHMmRhUytSTG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIK
      L3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVc0RlaHJLT2c2UjA4VUF1aU80ejNoMUY1bHVZd0NnWUlL
      b1pJemowRQpBd0lEU0FBd1JRSWhBT3ozaFpHTy9PamllRno5byt2RmdFRkV6MmpBcDRtSmRMRTlK
      cWMrZVV5bkFpQmVTQzhqCjBCSHVQTGFFOUhMWkRVQU1uM1FIRlNYR2R3Z0UwWG9BcWcyRjVRPT0K
      LS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSBWFkbWluGgZBZG1pbnMiMwoHUmVhZGVycxIoEh4I
      ARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigSHggBEhoS
      CBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIcEggSBggB
      EgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggBEhoSCBIG
      CAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9u
      UG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVs
      L09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGlcKEE9yZGVyZXJBZGRyZXNzZXMSQxIoCiZv
      cmRlcmVyMS5vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6ODQ0MxoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxomChBIYXNoaW5nQWxn
      b3JpdGhtEhISCAoGU0hBMjU2GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQ
      EgYI/////w8aBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdS
      ZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRl
      cnMaBkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoACgAKAA==
